### ISSUE TITLE
Best way to programmatically end mapply code in Jupyter

### ISSUE THREAD

**Issue by thoughtfuldata** [ddelange/mapply#18]
#### Description

What would be the best way to programmatically end mapply code early in Jupyter?

#### Use case / motivation / context
I did notice that you recently added code to terminate early on KeyboardInterrupt.  I am trying to catch the place where errors occurred by printing it and gracefully exit the code( A keyboard interrupt traceback would be okay). 

I have tried raise KeyboardInterrupt, _thread.interrupt_main(),  and sys.exit().  The Jupyter cell just hangs without stopping. 

ex.        except KeyError:
            print(f"KeyError videoID: {video_id[0]}")
            raise KeyboardInterrupt

I mean not catching the error would work as well, because then it will error out, but I wouldn't know where the error happened.

#### Related Issues

On a side note - it does seem like I have to restart the whole jupyter kernel( when using the vscode Keyboard Interrupt button as well) if I want to stop mapply code early.

**Comment by ddelange** [comment]
Hi @thoughtfuldata,

I've had a similar experience (having to restart the kernel), and indeed added a `pool.terminate` in the recent commits. The behaviour of terminate is definitely faster, as it sends a termination signal to the workers, but it might still take a while for all workers to terminate. The hanging you're experiencing is most likely waiting for the underlying `pool.join`, which blocks until all subprocesses have gracefully finished.

If you wait for the join to complete, you don't need have to restart the kernel and can run the cell again. If you send another stop signal (eg cancel the cell), the join will be interrupted and you'll have to restart the kernel.

So to answer your question, raising any exception or a KeyboardInterrupt is the right way, it might just take a while :) 

Hope that helps!
