### ISSUE TITLE
Does not work on windows

### ISSUE THREAD

**Issue by ma7555** [ddelange/mapply#37]
Hello, I tried using mappy on windows, however, only a single proccess is ever working regardless of `n_workers` parameter.
Does this work on windows or only unix systems?

My settings:
```
mapply.init(
    n_workers=12,
    max_chunks_per_worker=1,
    progressbar=True
)
```
```
  0%|   | 0/12 [00:00<?, ?it/s]
```
![image](https://user-images.githubusercontent.com/7144929/218652795-8ae64297-1d5d-4dfe-bcca-907fe77712d4.png)

**Comment by ddelange** [comment]
Hi @ma7555,

On Windows, there's only [`spawn`](https://github.com/uqfoundation/multiprocess/blob/multiprocess-0.70.14/py3.9/multiprocess/context.py#L256) method available. Meaning starting a new python process from scratch, running imports and sending pickled python objects to the new process. Depending on your environment, this might take a long time for them to actually start doing work.

As a test, could you restart your vscode (make sure no python processes are left), and run your computation on a setup with many chunks, like
```py
mapply.init(
    n_workers=2,
    chunk_size=1,
    max_chunks_per_worker=64,
    progressbar=True
)
```
and monitor your cpu usage for a bit?

**Comment by ma7555** [comment]
Hello @ddelange , I ended up using  process_map from tqdm concurrent futures.
