### ISSUE TITLE
mapply.init(n_workers=-1) only uses 1/2 of the maximum cpu cores

### ISSUE THREAD

**Issue by dohyeonscottkim** [ddelange/mapply#74]
`
mapply.init(
    n_workers = -1,
    progressbar = True,
)
`

I tried to use all of the cpu cores by above command.
But, when I look into cpu usage by `htop`, it looks like only using half of the cpu cores.

Is this normal?

![image](https://github.com/ddelange/mapply/assets/77238291/c466d6a5-49d4-49d1-a3f3-c03f80940bf1)

**Comment by ddelange** [comment]
Hi @dohyeonscottkim :wave:

Your cpu in the screenshot uses hyperthreading. That means that the number of logical cores is 2 x the number of physical cores.

For cpu-bound operations (e.g. number crunching), you will only create a fight for cpu cycles on the physical cores if you engage all logical cores. Most of the times that is not faster (rather slower). Logical cores are only fun if they don't want 100% cpu all the time (gaming, network i/o, disk i/o etc).

If you were using a system where logical cores == physical cores (e.g. ARM64 cpus), you would see all cores blasting in htop.

This is why mapply uses [`sensible_cpu_count`](https://mapply.readthedocs.io/en/stable/_code_reference/mapply.html#mapply.parallel.sensible_cpu_count).

You can benchmark total time yourself by manually setting n_workers.

Hope that helps!
